FROM node:latest as svelte-build

ENV HOSTPATH='http://192.168.0.49'

WORKDIR /app

COPY ./svelte-app  .

run npm install

run npm run build

FROM nginx:latest as svelte-app

COPY --from=svelte-build ./app/public /usr/share/nginx/html