FROM python:latest

ENV SQL='postgresql'

WORKDIR /app/fastapi/

COPY ./fastapi/ /app/fastapi/
COPY ./piplist.txt /app/fastapi/

RUN apt update
RUN apt install -y python3-certbot-nginx

RUN pip install -r piplist.txt

HEALTHCHECK --interval=5s --timeout=30s --start-period=5s --retries=3 CMD curl -f http://localhost:8000/api/check || exit 1

CMD gunicorn --bind 0.0.0.0:8000 main:app --worker-class uvicorn.workers.UvicornWorker

#CMD uvicorn main:app --reload --host 0.0.0.0 --port 8080 --workers 10con