version: '3.7'

services:
  fastapi-8000:
    image: fastapi:v2
    ports:
      - "8000:8000"
    networks:
      - app-net
    secrets:
      - source : pogresql-connetion
        target : /app/fastapi/sql_info.json

  fastapi-8001:
    image: fastapi:v2
    ports:
      - "8001:8000"
    networks:
      - app-net
    secrets:
      - source : pogresql-connetion
        target : /app/fastapi/sql_info.json

  svelte:
      image: svelte:v2
      ports:
        - "8005:80"
      networks:
        - app-net
      depends_on:
        - fastapi-8000
        - fastapi-8001
      
networks:
  app-net:
    external:
      name: nat
secrets:
  pogresql-connetion:
    file: ./sql_info.json
