"""empty message

Revision ID: 08ea73ee8a54
Revises: 1a658dc27459
Create Date: 2022-11-18 16:48:23.355480

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08ea73ee8a54'
down_revision = '1a658dc27459'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
