"""empty message

Revision ID: 10fbe6062b08
Revises: 2f268a2e629b
Create Date: 2022-11-18 16:40:38.440347

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '10fbe6062b08'
down_revision = '2f268a2e629b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('consumer_id', sa.Integer(), nullable=True))
    op.drop_constraint('purchase_ibfk_1', 'purchase', type_='foreignkey')
    op.create_foreign_key(None, 'purchase', 'consumer', ['consumer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase', 'cunsumer_id')
    op.add_column('sale', sa.Column('purchase_id', sa.Integer(), nullable=True))
    op.drop_constraint('sale_ibfk_2', 'sale', type_='foreignkey')
    op.create_foreign_key(None, 'sale', 'purchase', ['purchase_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sale', 'purchaselist_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sale', sa.Column('purchaselist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'sale', type_='foreignkey')
    op.create_foreign_key('sale_ibfk_2', 'sale', 'purchase', ['purchaselist_id'], ['id'], ondelete='CASCADE')
    op.drop_column('sale', 'purchase_id')
    op.add_column('purchase', sa.Column('cunsumer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'purchase', type_='foreignkey')
    op.create_foreign_key('purchase_ibfk_1', 'purchase', 'consumer', ['cunsumer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('purchase', 'consumer_id')
    # ### end Alembic commands ###
