"""empty message

Revision ID: 1845ade9e7aa
Revises: 6c6d4e7544a6
Create Date: 2022-11-18 14:37:10.646312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1845ade9e7aa'
down_revision = '6c6d4e7544a6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase', sa.Column('shipping_fee', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase', 'shipping_fee')
    # ### end Alembic commands ###
