"""empty message

Revision ID: 2a0da86e422c
Revises: 4845b41f2551
Create Date: 2022-11-17 13:58:46.493363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a0da86e422c'
down_revision = '4845b41f2551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('product', sa.Column('discount', sa.Integer(), nullable=True))
    op.add_column('product', sa.Column('shipping_fee', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'shipping_fee')
    op.drop_column('product', 'discount')
    # ### end Alembic commands ###
