"""empty message

Revision ID: 2a80684e683d
Revises: f5e970bf18d2
Create Date: 2022-11-18 16:54:37.307549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a80684e683d'
down_revision = 'f5e970bf18d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
