"""empty message

Revision ID: 2f268a2e629b
Revises: 1845ade9e7aa
Create Date: 2022-11-18 14:46:08.251264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f268a2e629b'
down_revision = '1845ade9e7aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
