"""empty message

Revision ID: 627009649a3e
Revises: d81da9e582ae
Create Date: 2022-11-17 19:54:14.334321

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '627009649a3e'
down_revision = 'd81da9e582ae'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
