"""empty message

Revision ID: 6c6d4e7544a6
Revises: d096fbf07253
Create Date: 2022-11-18 14:34:34.565790

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6c6d4e7544a6'
down_revision = 'd096fbf07253'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_number', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('cache', sa.Integer(), nullable=False),
    sa.Column('create_date', sa.DateTime(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('address1', sa.String(length=50), nullable=False),
    sa.Column('address2', sa.String(length=50), nullable=False),
    sa.Column('cunsumer_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cunsumer_id'], ['consumer.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sale',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchaselist_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchaselist_id'], ['purchase.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('salelist')
    op.drop_table('purchaselist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchaselist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('purchase_number', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('create_date', mysql.DATETIME(), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('phone_number', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('address1', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('address2', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('cunsumer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cache', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cunsumer_id'], ['consumer.id'], name='purchaselist_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='purchaselist_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'purchase_number', 'count'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.create_table('salelist',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('purchaselist_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('product_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], name='salelist_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['purchaselist_id'], ['purchaselist.id'], name='salelist_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8',
    mysql_engine='InnoDB'
    )
    op.drop_table('sale')
    op.drop_table('purchase')
    # ### end Alembic commands ###
