"""empty message

Revision ID: 986478ff702a
Revises: 2a80684e683d
Create Date: 2022-11-18 16:54:40.100775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '986478ff702a'
down_revision = '2a80684e683d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
