"""empty message

Revision ID: c22f737babdf
Revises: 10fbe6062b08
Create Date: 2022-11-18 16:42:52.266146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22f737babdf'
down_revision = '10fbe6062b08'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
