"""empty message

Revision ID: c4fda3e6ff1e
Revises: b78ee293e845
Create Date: 2022-11-18 16:57:12.818683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4fda3e6ff1e'
down_revision = 'b78ee293e845'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
