"""empty message

Revision ID: d096fbf07253
Revises: b126aee293f5
Create Date: 2022-11-18 14:18:55.612359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd096fbf07253'
down_revision = 'b126aee293f5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchaselist', sa.Column('cache', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchaselist', 'cache')
    # ### end Alembic commands ###
