"""empty message

Revision ID: d81da9e582ae
Revises: 2a0da86e422c
Create Date: 2022-11-17 19:54:00.269554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd81da9e582ae'
down_revision = '2a0da86e422c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
