"""empty message

Revision ID: f5e970bf18d2
Revises: 08ea73ee8a54
Create Date: 2022-11-18 16:48:27.335840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5e970bf18d2'
down_revision = '08ea73ee8a54'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
